// All audio processing happens within the same worklet, so this can be used to 
// share objects between worklet processors. They should be keyed by a unique 
// ID (e.g. generated by crypto.randomUUID() in the main thread).
export const registry = {};
